"""add_id_user_on_spot

Revision ID: 22093649178c
Revises: e57e16d566f7
Create Date: 2023-09-14 00:42:43.930077

"""
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "22093649178c"
down_revision = "e57e16d566f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("spot", "id_user", existing_type=postgresql.UUID(), nullable=False)
    op.create_unique_constraint(None, "spot", ["id_spot"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "spot", type_="unique")
    op.alter_column("spot", "id_user", existing_type=postgresql.UUID(), nullable=True)
    # ### end Alembic commands ###
