name: MasterCI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master
      
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./*
          host: ${{ secrets.SERVER_HOST }}
          remote: /home/ubuntu/
          user: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
