name: MasterCI

on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    name: Send files to host

    steps:
      - uses: actions/checkout@master
      
      - name: Copy files to host
        uses: nogsantos/scp-deploy@master
        with:
          src: ./*
          host: ${{ secrets.SERVER_HOST }}
          remote: /home/ubuntu/production_backend/
          user: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      - name: Run deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            CI=true docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            CI=true docker stop app_server database
            CI=true docker rm app_server database
            CI=true docker-compose -f /home/ubuntu/production_backend/docker-compose.yml up
        
