name: MasterCI

on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    name: Send files to host

    steps:
      - uses: actions/checkout@master
      
      - name: Copy files to host
        uses: nogsantos/scp-deploy@master
        with:
          src: ./*
          host: ${{ secrets.SERVER_HOST }}
          remote: /home/ubuntu/production_backend/
          user: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      - uses: alex-ac/github-action-ssh-docker-compose@master
        name: Docker-Compose Remote Deployment
        with:
          ssh_host: ${{ secrets.SERVER_HOST }}
          ssh_private_key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SERVER_USERNAME }}
          docker_compose_filename: /home/ubuntu/production_backend/docker-compose.yml
