name: MasterCI

on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    name: Send files to host

    steps:
      - uses: actions/checkout@master
      
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./*
          host: ${{ secrets.SERVER_HOST }}
          remote: /home/ubuntu/production_backend/
          user: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
